CREATE Proc SRC_JDEE1.vSalesOrder
AS
BEGIN
WITH QUERYSNIPPET as (
    SELECT DISTINCT 
     ADDRESSNUMBER AS CUSTOMERID
    ,NAMEALPHA CUSTOMER
    ,COSTCENTER COSTCENTERID
    ,ALTERNATEADDRESSKEY MNEMONICID
    ,CASE WHEN REPORTCODEADDBOOK017 <> 'E' THEN 1 ELSE 0 END HIERARCHYFILTER
    ,CASE WHEN ADDRESSNUMBER NOT IN ('10240', '10430', '10440', '10730', '10740', '18830', '18835', '18837', '333333', '530813', '999999') THEN 1 ELSE 0 END SHIPTOFILTER
    ,CASE WHEN COALESCE (COSTCENTER,'') NOT IN  ('10440', '18940', '10240', '18830', '188910001') THEN 1 ELSE 0 END BUSINESSUNITFILTER
    ,CASE WHEN COALESCE (REPORTCODEADDBOOK015,'') <> '' AND REPORTCODEADDBOOK015 NOT LIKE 'F%' AND SUBSTRING(REPORTCODEADDBOOK015,2,2) <> '99' THEN 1 ELSE 0 END SALESMANAGERFILTER
    FROM SRC_JDEE1.VADDRESSBOOKMASTER
    WHERE (ADDRESSTYPE1 LIKE 'C%' OR ADDRESSTYPE1 IN ('FC', 'IC') OR ADDRESSTYPE1 = 'PBE' OR ADDRESSNUMBER = 536680) AND ADDRESSTYPE1 NOT IN ('CAP')
)
SELECT 
    QUERYSNIPPET.*
    , ABM.ADDRESSTYPE1 AS SEARCHTYPEID
    , UDCST.DESCRIPTION001 AS SEARCHTYPE
    , ABM.REPORTCODEADDBOOK004 AS TERRITORYID
    , UDC13.DESCRIPTION001 AS PBCSCUSTOMERID
    , ABM.REPORTCODEADDBOOK017 AS HIERARCHYCHECKID
    , UDC17.DESCRIPTION001 AS HIERARCHYCHECK
    , UDC12.DESCRIPTION01002 AS MANUFACTURINGTYPE
    , UDC12.SPECIALHANDLINGCODE AS CUSTOMERCLASS
    , UDC13.DESCRIPTION01002 AS SALESTYPE
    , UDC13.SPECIALHANDLINGCODE AS CONTRACTCODE
    , ABM.REPORTCODEADDBOOK014 AS CUSTOMERTYPEID
    , UDC14.DESCRIPTION001 AS CUSTOMERTYPE
    ,case when ABM.REPORTCODEADDBOOK014 = ' ' then '-1' else REPORTCODEADDBOOK014 end AS CUSTOMERCODEID
    , UDC13.DESCRIPTION001 AS CUSTOMERCODE
    , case when ABM.REPORTCODEADDBOOK015 = ' ' then '-1' else REPORTCODEADDBOOK015 end AS SALESMANAGERID
    , UDC15.DESCRIPTION001 AS SALESMANAGER
    , UDC15.DESCRIPTION01002 AS SALESMANAGERREGION
    ,case when ABM.REPORTCODEADDBOOK014 = ' ' then '-1' else REPORTCODEADDBOOK014 end AS CUSTOMERAGGRLEVELID
    ,case when ABM.REPORTCODEADDBOOK014 = ' '  then '-1' else UDC13.DESCRIPTION001 end AS CUSTOMERAGGRLEVEL
    , case when ABM.REPORTCODEADDBOOK014 = ' ' then '-1' else REPORTCODEADDBOOK014 end AS PLANNINGLEVELID
    ,case when ABM.REPORTCODEADDBOOK014 = ' '  then '-1' else UDC13.DESCRIPTION001 end as PLANNINGLEVEL
    ,case when ABM.REPORTCODEADDBOOK012 = ' ' then '-1' else REPORTCODEADDBOOK012 end as CORPORATECODEID
    
    , UDC12.DESCRIPTION001 AS CORPORATECODE
    ,CASE WHEN CONCAT(HIERARCHYFILTER,SHIPTOFILTER) = 11 THEN 1 ELSE 0 END AS ACTUALSFILTER
    ,CASE WHEN CONCAT(HIERARCHYFILTER,SHIPTOFILTER,BUSINESSUNITFILTER,SALESMANAGERFILTER) = 1111 THEN 1 ELSE 0 END PLANNINGFILTER
    ,ABM.LAST_UPDATED_TS
    ,ABM.SRC_DELETED_FLG
FROM QUERYSNIPPET
LEFT JOIN SRC_JDEE1.VADDRESSBOOKMASTER as ABM ON QUERYSNIPPET.CUSTOMERID = ABM.ADDRESSNUMBER 
LEFT JOIN  SRC_JDEE1.VUSERDEFINEDCODEVALUES UDCST on ABM.ADDRESSTYPE1 = UDCST.USERDEFINEDCODE and UDCST.PRODUCTCODE = '01' and UDCST.USERDEFINEDCODES = 'ST'
--LEFT JOIN ADDRESSBOOKMASTER as U13 ON QUERYSNIPPET.CUSTOMERID = U13.ADDRESSNUMBER 
LEFT JOIN  SRC_JDEE1.VUSERDEFINEDCODEVALUES UDC13 on ABM.REPORTCODEADDBOOK014 = UDC13.USERDEFINEDCODE and UDC13.PRODUCTCODE = '01' and UDC13.USERDEFINEDCODES = '13'
--LEFT JOIN ADDRESSBOOKMASTER as U17 ON QUERYSNIPPET.CUSTOMERID = U17.ADDRESSNUMBER 
LEFT JOIN  SRC_JDEE1.VUSERDEFINEDCODEVALUES UDC17 on ABM.REPORTCODEADDBOOK017 = UDC17.USERDEFINEDCODE and UDC17.PRODUCTCODE = '01' and UDC17.USERDEFINEDCODES = '17'
--LEFT JOIN ADDRESSBOOKMASTER as U12 ON QUERYSNIPPET.CUSTOMERID = U12.ADDRESSNUMBER 
LEFT JOIN  SRC_JDEE1.VUSERDEFINEDCODEVALUES AS UDC12 on ABM.REPORTCODEADDBOOK012 = UDC12.USERDEFINEDCODE and UDC12.PRODUCTCODE = '01' and UDC12.USERDEFINEDCODES = '12'
--LEFT JOIN ADDRESSBOOKMASTER as U14 ON QUERYSNIPPET.CUSTOMERID = U14.ADDRESSNUMBER 
LEFT JOIN  SRC_JDEE1.VUSERDEFINEDCODEVALUES UDC14 on ABM.REPORTCODEADDBOOK014 = UDC14.USERDEFINEDCODE and UDC14.PRODUCTCODE = '01' and UDC14.USERDEFINEDCODES = '14'
--LEFT JOIN ADDRESSBOOKMASTER as U15 ON QUERYSNIPPET.CUSTOMERID = U15.ADDRESSNUMBER 
LEFT JOIN  SRC_JDEE1.VUSERDEFINEDCODEVALUES AS UDC15 on ABM.REPORTCODEADDBOOK015 = UDC15.USERDEFINEDCODE and UDC15.PRODUCTCODE = '01' and UDC15.USERDEFINEDCODES = '15'
END