/****** Object:  View [SRC_JDEE1].[vITEMMASTER]    Script Date: 01/05/2023 11.25.03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create View [SRC_JDEE1].[vITEMMASTER] AS
select 
IMOPV AS ORDERPOLICYVALUE
,IMACQ AS ACCTINGCOSTQTY
,IMMLQ AS MFGLEADTIMEQTY
,IMLTPU AS LEADTIMEPERUNIT
,IMMPSP AS PLANTIMEFENCERULE
,IMMRPP AS FIXEDVARIABLELEADTIME
,IMITC AS ISSUETYPECODE
,IMORDW AS ORDERWITHYN
,IMMTF1 AS PLANNINGTIMEFENCEDAYS
,IMMTF2 AS FREEZETIMEFENCEDAYS
,IMMTF3 AS MSGTIMEFENCEDAYS
,IMMTF4 AS TIMEFENCE4
,IMMTF5 AS TIMEFENCE5
,IMEXPD AS EXPEDITEDAMPERDAYS
,IMDEFD AS DEFERDAMPERDAYS
,IMSFLT AS SAFETYLEADTIME
,IMMAKE AS MAKEBUYCODE
,IMCOBY AS COPRODUCTSBYPRODUCTS
,IMLLX AS LOWLEVELCODE
,IMCMGL AS ALLOCATEBYLOT
,IMCOMH AS COMMITMENTSPECIFICDAYS
,IMURCD AS USERRESERVEDCODE
,IMURDT AS USERRESERVEDDATE
,IMURAT AS USERRESERVEDAMOUNT
,IMURAB AS USERRESERVEDNUMBER
,IMURRF AS USERRESERVEDREFERENCE
,IMUSER AS USERID
,IMPID AS PROGRAMID
,IMJOBN AS WORKSTATIONID
,IMUPMJ AS DATEUPDATED
,cast (
	CASE
	WHEN len(CAST(IMTDAY AS VARCHAR)) = 6 THEN
		LEFT(CAST(IMTDAY AS VARCHAR), 2) + ':' + substring(CAST(IMTDAY AS VARCHAR), 3, 2) + ':' + RIGHT(CAST(IMTDAY AS VARCHAR), 2)
	WHEN len(CAST(IMTDAY AS VARCHAR)) = 5 THEN
		'0' + LEFT(CAST(IMTDAY AS VARCHAR), 1) + ':' + substring(CAST(IMTDAY AS VARCHAR), 2, 2) + ':' + RIGHT(CAST(IMTDAY AS VARCHAR), 2)
	ELSE '00:00:00'
	END
as datetime)  AS TIMEOFDAY
,IMUPCN AS UPCNUMBER
,IMSCC0 AS AGGREGATESCCCODEPI0
,IMUMUP AS UNITOFMEASUREUPC
,IMUMDF AS UNITOFMEASUREAGGREGATEUPC
,IMUMS0 AS UNITOFMEASURESCCPI0
,IMUMS1 AS UNITOFMEASURESCCPI1
,IMUMS2 AS UNITOFMEASURESCCPI2
,IMUMS3 AS UNITOFMEASURESCCPI3
,IMUMS4 AS UNITOFMEASURESCCPI4
,IMUMS5 AS UNITOFMEASURESCCPI5
,IMUMS6 AS UNITOFMEASURESCCPI6
,IMUMS7 AS UNITOFMEASURESCCPI7
,IMUMS8 AS UNITOFMEASURESCCPI8
,IMPOC AS PAYONCONSUMPTION
,IMAVRT AS AVERAGEQUEUETIMEHOURS
,IMEQTY AS PALLETTYPE
,IMWTRQ AS ITEMWEIGHTREQUIRED
,IMTMPL AS TEMPLATE
,IMSEG1 AS SEGMENT1
,IMSEG2 AS SEGMENT2
,IMSEG3 AS SEGMENT3
,IMSEG4 AS SEGMENT4
,IMSEG5 AS SEGMENT5
,IMSEG6 AS SEGMENT6
,IMSEG7 AS SEGMENT7
,IMSEG8 AS SEGMENT8
,IMSEG9 AS SEGMENT9
,IMSEG0 AS SEGMENT10
,IMMIC AS MATRIXCONTROLLED
,IMAING AS ACTIVEINGREDIENTFLAG
,IMBBDD AS BESTBEFOREDEFAULTDAYS
,IMCMDM AS COMMITMENTDATEMETHOD
,IMLECM AS LOTEXPIRATIONDATECALCULATIONMETHOD
,IMLEDD AS LOTEFFECTIVEDEFAULTDAYS
,IMPEFD AS PURCHASINGEFFECTIVEDAYS
,IMSBDD AS SELLBYDEFAULTDAYS
,IMU1DD AS USERLOTDATE1DEFAULTDAYS
,IMU2DD AS USERLOTDATE2DEFAULTDAYS
,IMU3DD AS USERLOTDATE3DEFAULTDAYS
,IMU4DD AS USERLOTDATE4DEFAULTDAYS
,IMU5DD AS USERLOTDATE5DEFAULTDAYS
,IMDLTL AS DUALTOLERANCE
,IMDPPO AS DUALPICKINGPROCESSOPTION
,IMDUAL AS DUALUNITOFMEASUREITEM
,IMXDCK AS CROSSDOCKFLAG
,IMLAF AS LOTAUDITFLAG
,IMLTFM AS SPECIALLOTFORMAT
,IMRWLA AS RESTRICTWOLOTASSIGNMENT
,IMLNPA AS LOTNUMBERPREASIGNMENT
,IMLOTC AS LOTSTATUSCODEEXPANDED
,IMAPSC AS CONSTRAINTSFLAG
,IMAUOM AS APSPLANNINGUOM
,IMCONB AS CONSUMABLE
,IMGCMP AS COMPOSITION
,IMPRI1 AS PRIORITYONEALERTLEVEL
,IMPRI2 AS PRIORITYTWOALERTLEVEL
,IMASHL AS ALLOWSHIPPINGHELDLOTS
,IMVMINV AS VENDORMANAGEDINVENTORY
,IMCMETH AS METHODOFCOSTCALCULA
,IMEXPI AS EXPLODEITEM10
,IMOPTH AS MINOPERATIONALTHRESHOLD
,IMCUTH AS MINCUMULATIVETHRESHOLD
,IMUMTH AS OPERATIONALTHRESHOLDUOM
,IMLMFG AS LEANFLAG
,IMLINE AS LINEIDENTIFIER
,IMDFTPCT AS TOTALPRODUCTCYCLETIME
,IMKBIT AS KANBANITEM
,IMDFENDITM AS DFENDITEMFLAG
,IMKANEXLL AS KANBANEXPLODETOLOWERLEVEL
,IMSCPSELL AS SELLABLE
,IMMOPTH AS MAXOPERATIONALTHRESHOLD
,IMMCUTH AS MAXCUMULATIVETHRESHOLD
,IMCUMTH AS CUMULATIVETHRESHOLDUOM
,IMATPRN AS ATPRULENAME
,IMATPCA AS CHECKATP
,IMATPAC AS ATPCOMPONENTS
,IMCOORE AS COUNTRYOFORIGINREQUIRED
,IMVCPFC AS ATOFORECASTCONTROL
,IMPNYN AS PRODUCTIONNUMBERCONTROLLED
,IMITM AS IDENTIFIERSHORTITEM
,IMLITM AS IDENTIFIER2NDITEM
,IMAITM AS IDENTIFIER3RDITEM
,IMDSC1 AS DESCRIPTIONLINE1
,IMDSC2 AS DESCRIPTIONLINE2
,IMSRTX AS SEARCHTEXT
,IMALN AS SEARCHTEXTCOMPRESSED
,IMSRP1 AS SALESREPORTINGCODE1
,IMSRP2 AS SALESREPORTINGCODE2
,IMSRP3 AS SALESREPORTINGCODE3
,IMSRP4 AS SALESREPORTINGCODE4
,IMSRP5 AS SALESREPORTINGCODE5
,IMSRP6 AS SALESREPORTINGCODE6
,IMSRP7 AS SALESREPORTINGCODE7
,IMSRP8 AS SALESREPORTINGCODE8
,IMSRP9 AS SALESREPORTINGCODE9
,IMSRP0 AS SALESREPORTINGCODE10
,IMPRP1 AS PURCHASINGREPORTCODE1
,IMPRP2 AS PURCHASINGREPORTCODE2
,IMPRP3 AS PURCHASINGREPORTCODE3
,IMPRP4 AS PURCHASINGREPORTCODE4
,IMPRP5 AS PURCHASINGREPORTCODE5
,IMPRP6 AS PURCHREPORTINGCODE6
,IMPRP7 AS PURCHREPORTINGCODE7
,IMPRP8 AS PURCHREPORTINGCODE8
,IMPRP9 AS PURCHREPORTINGCODE9
,IMPRP0 AS PURCHREPORTINGCODE10
,IMCDCD AS COMMODITYCODE
,IMPDGR AS PRODUCTGROUPFROM
,IMDSGP AS DISPATCHGRP
,IMPRGR AS PRICINGCATEGORY
,IMRPRC AS REPRICEBASKETPRICECAT
,IMORPR AS ORDERREPRICECATEGORY
,IMBUYR AS BUYER
,IMDRAW AS DRAWINGNUMBER
,IMRVNO AS REVISIONNUMBER
,IMDSZE AS DRAWINGSIZE
,IMVCUD AS VOLUMECUBICDIMENSIONS
,IMCARS AS CARRIER
,IMCARP AS PREFERCARRIERPURCHASIN
,IMSHCN AS SHIPPINGCONDITIONSCODE
,IMSHCM AS SHIPPINGCOMMODITYCLASS
,IMUOM1 AS UNITOFMEASUREPRIMARY
,IMUOM2 AS UNITOFMEASURESECONDARY
,IMUOM3 AS UNITOFMEASUREPURCHAS
,IMUOM4 AS UNITOFMEASUREPRICING
,IMUOM6 AS UNITOFMEASURESHIPPING
,IMUOM8 AS UNITOFMEASUREPRODUCTION
,IMUOM9 AS UNITOFMEASUREALLOCATION
,IMUWUM AS UNITOFMEASUREWEIGHT
,IMUVM1 AS UNITOFMEASUREVOLUME
,IMSUTM AS UNITOFMEASURESTOCKI
,IMUMVW AS UNITOFMEASUREVOLUMEORWEI
,IMCYCL AS CYCLECOUNTCATEGORY
,IMGLPT AS GLCATEGORY
,IMPLEV AS PRICELEVEL
,IMPPLV AS LEVELPURCHASINGPRICE
,IMCLEV AS COSTLEVEL
,IMPRPO AS POTENCYPRICING
,IMCKAV AS CHECKAVAILABILITYYN
,IMBPFG AS BULKPACKEDFLAG
,IMSRCE AS LAYERCODESOURCE
,IMOT1Y AS CONSTANTFUTUREUSE1
,IMOT2Y AS CONSTANTFUTUREUSE2
,IMSTDP AS STANDARDPOTENCY
,IMFRMP AS FROMPOTENCY
,IMTHRP AS THRUPOTENCY
,IMSTDG AS STANDARDGRADE
,IMFRGD AS FROMGRADE
,IMTHGD AS THRUGRADE
,IMCOTY AS COMPONENTTYPE
,IMSTKT AS STOCKINGTYPE
,IMLNTY AS LINETYPE
,IMCONT AS CONTRACTITEM
,IMBACK AS BACKORDERSALLOWEDYN
,IMIFLA AS ITEMFLASHMESSAGE
,IMTFLA AS TEMPORARYITEMFLASHMESSAG
,IMINMG AS PRINTMESSAGE1
,IMABCS AS ABCCODE1SALESINV
,IMABCM AS ABCCODE2MARGININV
,IMABCI AS ABCCODE3INVESTINV
,IMOVR AS ABCCODEOVERRIDEINDICA
,IMWARR AS TYPEWARRANTY
,IMCMCG AS COMMISSIONCATEGORY
,IMSRNR AS SERIALNUMBERREQUIRED
,IMPMTH AS METHODOFPRICECALCULA
,IMFIFO AS FIFOPROCESSING
,IMLOTS AS LOTSTATUSCODE
,IMSLD AS SHELFLIFEDAYS
,IMANPL AS ADDRESSNUMBERPLANNER
,IMMPST AS PLANNINGCODE
,IMPCTM AS PERCENTMARGIN
,IMMMPC AS MARGINMAINTENANCEPER
,IMPTSC AS PARTSTATUSCODE
,IMSNS AS STOCKNONSTOCK
,IMLTLV AS LEADTIMELEVEL
,IMLTMF AS LEADTIMEMFG
,IMLTCM AS LEADTIMECUM
,IMOPC AS ORDERPOLICYCODE
, CASE
    WHEN len(cast(IMURDT as VARCHAR)) = 6 THEN 
		DATEADD(day, 
		RIGHT(CAST(IMURDT AS VARCHAR), 3) - 1, 
		DATEADD(
			year, 
			cast(SUBSTRING(CAST(IMURDT AS varchar), 2, 2) as  int),
			DATEFROMPARTS(2000, 1, 1)
			)
        )
    ELSE 
    DATEADD(day, 
		RIGHT(CAST(IMURDT AS VARCHAR), 3) - 1, 
		DATEADD(
			year, 
			cast(SUBSTRING(CAST(IMURDT AS varchar), 1, 2) as  int),
			DATEFROMPARTS(1900, 1, 1))
    )
END AS USERRESERVEDDATE_DATE
, cast(CASE
    WHEN len(cast(IMURDT as VARCHAR)) = 6 THEN 
		DATEADD(day, 
		RIGHT(CAST(IMURDT AS VARCHAR), 3) - 1, 
		DATEADD(
			year, 
			cast(SUBSTRING(CAST(IMURDT AS varchar), 2, 2) as  int),
			DATEFROMPARTS(2000, 1, 1))
        )
    ELSE 
    DATEADD(day, 
		RIGHT(CAST(IMURDT AS VARCHAR), 3) - 1, 
		DATEADD(
			year, 
			cast(SUBSTRING(CAST(IMURDT AS varchar), 1, 2) as  int),
			DATEFROMPARTS(1900, 1, 1))
    )
END as varchar) AS USERRESERVEDDATE_YM
, CASE
    WHEN len(cast(IMUPMJ as VARCHAR)) = 6 THEN 
        DATEADD(day,
                right(cast(IMUPMJ as VARCHAR), 3) - 1, 
                DATEADD(
                        year,
                        cast(SUBSTRING(cast(IMUPMJ as VARCHAR), 2, 2) as int), 
                        DATEFROMPARTS(2000,1,1)
                )
        )
    ELSE 
        DATEADD(day,
            right(cast(IMUPMJ as VARCHAR), 3) - 1, 
            DATEADD(
                    year,
                    cast(SUBSTRING(cast(IMUPMJ as VARCHAR), 1, 2) as int),
                    DATEFROMPARTS(1900,1,1)
            )
    )
END AS DATEUPDATED_DATE
, cast(CASE
    WHEN len(cast(IMUPMJ as VARCHAR)) = 6 THEN 
        DATEADD(day,
                right(cast(IMUPMJ as VARCHAR), 3) - 1, 
                DATEADD(
                        year,
                        cast(SUBSTRING(cast(IMUPMJ as VARCHAR), 2, 2) as int),
                        DATEFROMPARTS(2000,1,1)
                )
        )
    ELSE 
        DATEADD(day,
            right(cast(IMUPMJ as VARCHAR), 3) - 1, 
            DATEADD(
                    year,
                    cast(SUBSTRING(cast(IMUPMJ as VARCHAR), 1, 2) as  int),
                    DATEFROMPARTS(1900,1,1)
            )
    )
END as varchar) AS DATEUPDATED_YM
,IMITM AS IDENTIFIERSHORTITEM_TRIM
--, TRIM(IMITM) AS IDENTIFIERSHORTITEM_TRIM
,SRC_DELETED_FLG 
,LAST_UPDATED_TS 
FROM dbo.F4101
GO


