SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [STG_JDEE1].[F4211](
	[SDKCOO] [nchar](5) NULL,
	[SDDOCO] [int] NULL,
	[SDDCTO] [nchar](2) NULL,
	[SDLNID] [decimal](6, 3) NULL,
	[SDSFXO] [nchar](3) NULL,
	[SDMCU] [nchar](12) NULL,
	[SDCO] [nchar](5) NULL,
	[SDOKCO] [nchar](5) NULL,
	[SDOORN] [nchar](8) NULL,
	[SDOCTO] [nchar](2) NULL,
	[SDOGNO] [decimal](7, 3) NULL,
	[SDRKCO] [nchar](5) NULL,
	[SDRORN] [nchar](8) NULL,
	[SDRCTO] [nchar](2) NULL,
	[SDRLLN] [decimal](7, 3) NULL,
	[SDDMCT] [nchar](12) NULL,
	[SDDMCS] [int] NULL,
	[SDAN8] [int] NULL,
	[SDSHAN] [int] NULL,
	[SDPA8] [int] NULL,
	[SDDRQJ] [numeric](6, 0) NULL,
	[SDTRDJ] [numeric](6, 0) NULL,
	[SDPDDJ] [numeric](6, 0) NULL,
	[SDADDJ] [numeric](6, 0) NULL,
	[SDIVD] [numeric](6, 0) NULL,
	[SDCNDJ] [numeric](6, 0) NULL,
	[SDDGL] [numeric](6, 0) NULL,
	[SDRSDJ] [numeric](6, 0) NULL,
	[SDPEFJ] [numeric](6, 0) NULL,
	[SDPPDJ] [numeric](6, 0) NULL,
	[SDVR01] [nchar](25) NULL,
	[SDVR02] [nchar](25) NULL,
	[SDITM] [int] NULL,
	[SDLITM] [nchar](25) NULL,
	[SDAITM] [nchar](25) NULL,
	[SDLOCN] [nchar](20) NULL,
	[SDLOTN] [nchar](30) NULL,
	[SDFRGD] [nchar](3) NULL,
	[SDTHGD] [nchar](3) NULL,
	[SDFRMP] [decimal](7, 3) NULL,
	[SDTHRP] [decimal](7, 3) NULL,
	[SDEXDP] [int] NULL,
	[SDDSC1] [nchar](30) NULL,
	[SDDSC2] [nchar](30) NULL,
	[SDLNTY] [nchar](2) NULL,
	[SDNXTR] [nchar](3) NULL,
	[SDLTTR] [nchar](3) NULL,
	[SDEMCU] [nchar](12) NULL,
	[SDRLIT] [nchar](8) NULL,
	[SDKTLN] [decimal](6, 3) NULL,
	[SDCPNT] [decimal](4, 1) NULL,
	[SDRKIT] [int] NULL,
	[SDKTP] [decimal](15, 2) NULL,
	[SDSRP1] [nchar](3) NULL,
	[SDSRP2] [nchar](3) NULL,
	[SDSRP3] [nchar](3) NULL,
	[SDSRP4] [nchar](3) NULL,
	[SDSRP5] [nchar](3) NULL,
	[SDPRP1] [nchar](3) NULL,
	[SDPRP2] [nchar](3) NULL,
	[SDPRP3] [nchar](3) NULL,
	[SDPRP4] [nchar](3) NULL,
	[SDPRP5] [nchar](3) NULL,
	[SDUOM] [nchar](2) NULL,
	[SDUORG] [decimal](15, 2) NULL,
	[SDSOQS] [decimal](15, 2) NULL,
	[SDSOBK] [decimal](15, 2) NULL,
	[SDSOCN] [decimal](15, 2) NULL,
	[SDSONE] [decimal](15, 2) NULL,
	[SDUOPN] [decimal](15, 2) NULL,
	[SDQTYT] [decimal](15, 2) NULL,
	[SDQRLV] [decimal](15, 2) NULL,
	[SDCOMM] [nchar](1) NULL,
	[SDOTQY] [nchar](1) NULL,
	[SDUPRC] [decimal](15, 4) NULL,
	[SDAEXP] [decimal](15, 2) NULL,
	[SDAOPN] [decimal](15, 2) NULL,
	[SDPROV] [nchar](1) NULL,
	[SDTPC] [nchar](1) NULL,
	[SDAPUM] [nchar](2) NULL,
	[SDLPRC] [decimal](15, 4) NULL,
	[SDUNCS] [decimal](15, 4) NULL,
	[SDECST] [decimal](15, 2) NULL,
	[SDCSTO] [nchar](1) NULL,
	[SDTCST] [decimal](15, 4) NULL,
	[SDINMG] [nchar](10) NULL,
	[SDPTC] [nchar](3) NULL,
	[SDRYIN] [nchar](1) NULL,
	[SDDTBS] [nchar](1) NULL,
	[SDTRDC] [decimal](7, 3) NULL,
	[SDFUN2] [decimal](15, 4) NULL,
	[SDASN] [nchar](8) NULL,
	[SDPRGR] [nchar](8) NULL,
	[SDCLVL] [nchar](3) NULL,
	[SDCADC] [decimal](7, 3) NULL,
	[SDKCO] [nchar](5) NULL,
	[SDDOC] [int] NULL,
	[SDDCT] [nchar](2) NULL,
	[SDODOC] [int] NULL,
	[SDODCT] [nchar](2) NULL,
	[SDOKC] [nchar](5) NULL,
	[SDPSN] [int] NULL,
	[SDDELN] [int] NULL,
	[SDTAX1] [nchar](1) NULL,
	[SDTXA1] [nchar](10) NULL,
	[SDEXR1] [nchar](2) NULL,
	[SDATXT] [nchar](1) NULL,
	[SDPRIO] [nchar](1) NULL,
	[SDRESL] [nchar](1) NULL,
	[SDBACK] [nchar](1) NULL,
	[SDSBAL] [nchar](1) NULL,
	[SDAPTS] [nchar](1) NULL,
	[SDLOB] [nchar](3) NULL,
	[SDEUSE] [nchar](3) NULL,
	[SDDTYS] [nchar](2) NULL,
	[SDNTR] [nchar](2) NULL,
	[SDVEND] [int] NULL,
	[SDCARS] [int] NULL,
	[SDMOT] [nchar](3) NULL,
	[SDROUT] [nchar](3) NULL,
	[SDSTOP] [nchar](3) NULL,
	[SDZON] [nchar](3) NULL,
	[SDCNID] [nchar](20) NULL,
	[SDFRTH] [nchar](3) NULL,
	[SDSHCM] [nchar](3) NULL,
	[SDSHCN] [nchar](3) NULL,
	[SDSERN] [nchar](30) NULL,
	[SDUOM1] [nchar](2) NULL,
	[SDPQOR] [decimal](15, 2) NULL,
	[SDUOM2] [nchar](2) NULL,
	[SDSQOR] [decimal](15, 2) NULL,
	[SDUOM4] [nchar](2) NULL,
	[SDITWT] [decimal](15, 4) NULL,
	[SDWTUM] [nchar](2) NULL,
	[SDITVL] [decimal](15, 4) NULL,
	[SDVLUM] [nchar](2) NULL,
	[SDRPRC] [nchar](8) NULL,
	[SDORPR] [nchar](8) NULL,
	[SDORP] [nchar](1) NULL,
	[SDCMGP] [nchar](2) NULL,
	[SDGLC] [nchar](4) NULL,
	[SDCTRY] [int] NULL,
	[SDFY] [int] NULL,
	[SDSO01] [nchar](1) NULL,
	[SDSO02] [nchar](1) NULL,
	[SDSO03] [nchar](1) NULL,
	[SDSO04] [nchar](1) NULL,
	[SDSO05] [nchar](1) NULL,
	[SDSO06] [nchar](1) NULL,
	[SDSO07] [nchar](1) NULL,
	[SDSO08] [nchar](1) NULL,
	[SDSO09] [nchar](1) NULL,
	[SDSO10] [nchar](1) NULL,
	[SDSO11] [nchar](1) NULL,
	[SDSO12] [nchar](1) NULL,
	[SDSO13] [nchar](1) NULL,
	[SDSO14] [nchar](1) NULL,
	[SDSO15] [nchar](1) NULL,
	[SDACOM] [nchar](1) NULL,
	[SDCMCG] [nchar](8) NULL,
	[SDRCD] [nchar](3) NULL,
	[SDGRWT] [decimal](15, 4) NULL,
	[SDGWUM] [nchar](2) NULL,
	[SDSBL] [nchar](8) NULL,
	[SDSBLT] [nchar](1) NULL,
	[SDLCOD] [nchar](2) NULL,
	[SDUPC1] [nchar](2) NULL,
	[SDUPC2] [nchar](2) NULL,
	[SDUPC3] [nchar](2) NULL,
	[SDSWMS] [nchar](1) NULL,
	[SDUNCD] [nchar](1) NULL,
	[SDCRMD] [nchar](1) NULL,
	[SDCRCD] [nchar](3) NULL,
	[SDCRR] [int] NULL,
	[SDFPRC] [decimal](15, 4) NULL,
	[SDFUP] [decimal](15, 4) NULL,
	[SDFEA] [decimal](15, 2) NULL,
	[SDFUC] [decimal](15, 4) NULL,
	[SDFEC] [decimal](15, 2) NULL,
	[SDURCD] [nchar](2) NULL,
	[SDURDT] [numeric](6, 0) NULL,
	[SDURAT] [decimal](15, 2) NULL,
	[SDURAB] [int] NULL,
	[SDURRF] [nchar](15) NULL,
	[SDTORG] [nchar](10) NULL,
	[SDUSER] [nchar](10) NULL,
	[SDPID] [nchar](10) NULL,
	[SDJOBN] [nchar](10) NULL,
	[SDUPMJ] [numeric](6, 0) NULL,
	[SDTDAY] [int] NULL,
	[SDSO16] [nchar](1) NULL,
	[SDSO17] [nchar](1) NULL,
	[SDSO18] [nchar](1) NULL,
	[SDSO19] [nchar](1) NULL,
	[SDSO20] [nchar](1) NULL,
	[SDIR01] [nchar](30) NULL,
	[SDIR02] [nchar](30) NULL,
	[SDIR03] [nchar](30) NULL,
	[SDIR04] [nchar](30) NULL,
	[SDIR05] [nchar](30) NULL,
	[SDSOOR] [numeric](38, 0) NULL,
	[SDVR03] [nchar](25) NULL,
	[SDDEID] [int] NULL,
	[SDPSIG] [nchar](30) NULL,
	[SDRLNU] [nchar](10) NULL,
	[SDPMDT] [int] NULL,
	[SDRLTM] [int] NULL,
	[SDRLDJ] [numeric](6, 0) NULL,
	[SDDRQT] [int] NULL,
	[SDADTM] [int] NULL,
	[SDOPTT] [int] NULL,
	[SDPDTT] [int] NULL,
	[SDPSTM] [int] NULL,
	[SDXDCK] [nchar](1) NULL,
	[SDXPTY] [int] NULL,
	[SDDUAL] [nchar](1) NULL,
	[SDBSC] [nchar](10) NULL,
	[SDCBSC] [nchar](10) NULL,
	[SDCORD] [int] NULL,
	[SDDVAN] [int] NULL,
	[SDPEND] [nchar](1) NULL,
	[SDRFRV] [nchar](3) NULL,
	[SDMCLN] [decimal](6, 3) NULL,
	[SDSHPN] [int] NULL,
	[SDRSDT] [int] NULL,
	[SDPRJM] [int] NULL,
	[SDOSEQ] [int] NULL,
	[SDMERL] [nchar](3) NULL,
	[SDHOLD] [nchar](2) NULL,
	[SDHDBU] [nchar](12) NULL,
	[SDDMBU] [nchar](12) NULL,
	[SDBCRC] [nchar](3) NULL,
	[SDODLN] [decimal](7, 3) NULL,
	[SDOPDJ] [numeric](6, 0) NULL,
	[SDXKCO] [nchar](5) NULL,
	[SDXORN] [int] NULL,
	[SDXCTO] [nchar](2) NULL,
	[SDXLLN] [decimal](6, 3) NULL,
	[SDXSFX] [nchar](3) NULL,
	[SDPOE] [nchar](6) NULL,
	[SDPMTO] [nchar](1) NULL,
	[SDANBY] [int] NULL,
	[SDPMTN] [nchar](12) NULL,
	[SDNUMB] [int] NULL,
	[SDAAID] [int] NULL,
	[SDSPATTN] [nchar](50) NULL,
	[SDPRAN8] [int] NULL,
	[SDPRCIDLN] [int] NULL,
	[SDCCIDLN] [int] NULL,
	[SDSHCCIDLN] [int] NULL,
	[SDOPPID] [int] NULL,
	[SDOSTP] [nchar](3) NULL,
	[SDUKID] [int] NULL,
	[SDCATNM] [nchar](30) NULL,
	[SDALLOC] [nchar](1) NULL,
	[SDFULPID] [numeric](38, 0) NULL,
	[SDALLSTS] [nchar](30) NULL,
	[SDOSCORE] [decimal](15, 3) NULL,
	[SDOSCOREO] [nchar](1) NULL,
	[SDCMCO] [nchar](5) NULL,
	[SDKITID] [int] NULL,
	[SDKITAMTDOM] [decimal](15, 2) NULL,
	[SDKITAMTFOR] [decimal](15, 2) NULL,
	[SDKITDIRTY] [nchar](1) NULL,
	[SDOCITT] [nchar](1) NULL,
	[SDOCCARDNO] [int] NULL,
	[SDPMPN] [nchar](30) NULL,
	[SDPNS] [int] NULL
) ON [PRIMARY]
GO
